FROM condaforge/mambaforge

RUN apt-get update && apt-get install -y \
    less \
    vim

ARG NLP_API_CONTAINER_PORT
ENV APP_HOME /api
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

VOLUME ["/tmp"]

COPY conda_requirements.txt $APP_HOME
COPY conda_pip_requirements.txt $APP_HOME
COPY config.py $APP_HOME
COPY install_models.py $APP_HOME

RUN mamba create --name claritynlp python=3.10

RUN echo "conda activate claritynlp" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

RUN mamba config --env --add channels conda-forge
RUN mamba config --env --set channel_priority strict
RUN mamba install --file conda_requirements.txt
RUN pip install -r conda_pip_requirements.txt
RUN python3 -m spacy download en_core_web_sm
RUN python3 install_models.py

COPY . .
ENV PATH /opt/conda/envs/claritynlp/bin:$PATH
CMD ["gunicorn", "api", "--config", "config.py", "-b", "$NLP_API_CONTAINER_PORT"]
