version: '3'

volumes:
  mapper-pgdata:
  mapper-redisdata:
  nlp-solrdata:
  nlp-pgdata:
  nlp-mongodata:

services:

  nlp-api:
    container_name: 'NLP_API'
    hostname: ${NLP_API_HOSTNAME}
    build:
      context: ./nlp
      dockerfile: Dockerfile.prod
    ports:
      - "${NLP_API_HOST_PORT}:${NLP_API_CONTAINER_PORT}"
    command: ["/api/scripts/wait-for-it.sh", "${NLP_SOLR_HOSTNAME}:${NLP_SOLR_CONTAINER_PORT}", "${NLP_MONGO_HOSTNAME}:${NLP_MONGO_CONTAINER_PORT}", "${SCHEDULER_HOSTNAME}:${SCHEDULER_CONTAINER_PORT}", "${NLP_PG_HOSTNAME}:${NLP_PG_CONTAINER_PORT}", "--timeout=1800", "--", "python3", "api.py"]
    env_file:
      - .env

  scheduler:
    container_name: 'LUIGI_SCHEDULER'
    hostname: ${SCHEDULER_HOSTNAME}
    image: 'axiom/docker-luigi:2.7.1'
    ports:
      - "${SCHEDULER_HOST_PORT}:${SCHEDULER_CONTAINER_PORT}"
    env_file:
      - .env

  nlp-solr:
    container_name: 'NLP_SOLR'
    hostname: ${NLP_SOLR_HOSTNAME}
    build:
      context: ./utilities/nlp-solr
      dockerfile: Dockerfile.prod
    ports:
      - "${NLP_SOLR_HOST_PORT}:${NLP_SOLR_CONTAINER_PORT}"
    volumes:
      - 'nlp-solrdata:/opt/solr/server/solr/mycores'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ${NLP_CORE_NAME}
    environment:
      - SOLR_HEAP=8192m
    env_file:
      - .env

  nlp-mongo:
    container_name: 'NLP_MONGO'
    hostname: ${NLP_MONGO_HOSTNAME}
    build:
      context: ./utilities/nlp-mongo
      dockerfile: Dockerfile.prod
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=${NLP_MONGO_DATABASE}
    ports:
      - "${NLP_MONGO_HOST_PORT}:${NLP_MONGO_CONTAINER_PORT}"
    volumes:
      - 'nlp-mongodata:/data/db'
    env_file:
      - .env

  nlp-postgres:
    container_name: 'NLP_POSTGRES'
    hostname: ${NLP_PG_HOSTNAME}
    build:
      context: ./utilities/nlp-postgres
      dockerfile: Dockerfile.prod
    environment:
      POSTGRES_USER: ${NLP_PG_USER}
      POSTGRES_PASSWORD: ${NLP_PG_PASSWORD}
      POSTGRES_DB: ${NLP_PG_DATABASE}
    ports:
      - "${NLP_PG_HOST_PORT}:${NLP_PG_CONTAINER_PORT}"
    volumes:
      - 'nlp-pgdata:/var/lib/postgresql/data/'
    env_file:
      - .env

  ingest-api:
    container_name: INGEST_API
    hostname: ${INGEST_API_HOSTNAME}
    build: ./utilities/ingest-api
    ports:
      - "${INGEST_API_HOST_PORT}:${INGEST_API_CONTAINER_PORT}"
    depends_on:
      # - ingest-pg
      - redis
    environment:
      - NODE_ENV=production
    command: "pm2-runtime app.js"
    env_file:
      - .env

  # ingest-client:
  #   container_name: INGEST_CLIENT
  #   hostname: ${INGEST_CLIENT_HOSTNAME}
  #   build:
  #     context: ./utilities/ingest-client
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "${INGEST_CLIENT_HOST_PORT}:${INGESET_CLIENT_CONTAINER_PORT}"

  # ingest-pg:
  #   container_name: 'INGEST_POSTGRES'
  #   hostname: ${INGEST_PG_HOSTNAME}
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${INGEST_PG_USER}
  #     POSTGRES_PASSWORD: ${INGEST_PG_PASSWORD}
  #     POSTGRES_DB: ${INGEST_PG_DATABASE}
  #   ports:
  #     - "${INGEST_PG_HOST_PORT}:${INGEST_PG_CONTAINER_PORT}"
  #   volumes:
  #     - 'ingest-pgdata:/var/lib/postgresql/data/'

  mapper-api:
    container_name: MAPPER_API
    hostname: ${MAPPER_API_HOSTNAME}
    build: ./utilities/mapper-api
    ports:
      - "${MAPPER_API_HOST_PORT}:${MAPPER_API_CONTAINER_PORT}"
    depends_on:
      - mapper-pg
      - redis
    environment:
      - NODE_ENV=production
    command: "pm2-runtime app.js"
    env_file:
      - .env

  mapper-pg:
    container_name: 'MAPPER_POSTGRES'
    hostname: ${MAPPER_PG_HOSTNAME}
    image: postgres
    environment:
      POSTGRES_USER: ${MAPPER_PG_USER}
      POSTGRES_PASSWORD: ${MAPPER_PG_PASSWORD}
      POSTGRES_DB: ${MAPPER_PG_DATABASE}
    ports:
      - "${MAPPER_PG_HOST_PORT}:${MAPPER_PG_CONTAINER_PORT}"
    volumes:
      - 'mapper-pgdata:/var/lib/postgresql/data/'
    env_file:
      - .env

  redis:
    container_name: MAPPER_REDIS
    hostname: ${MAPPER_REDIS_HOSTNAME}
    image: redis:3.2.0
    ports:
      - "${MAPPER_REDIS_HOST_PORT}:${MAPPER_REDIS_CONTAINER_PORT}"
    volumes:
      - 'mapper-redisdata:/data'
    env_file:
      - .env

  swagger:
    container_name: MAPPER_SWAGGER
    hostname: ${MAPPER_SWAGGER_HOSTNAME}
    image: swaggerapi/swagger-ui
    environment:
    - "API_URL=${MAPPER_SWAGGER_API_URL}"
    ports:
      - "${MAPPER_SWAGGER_HOST_PORT}:${MAPPER_SWAGGER_CONTAINER_PORT}"
    env_file:
      - .env
