IRREGULAR_VERBS = {
'abide':[['abided'],['abided']],
'ache':[['ached'],['ached']],
'alight':[['alit', 'alighted'],['alit', 'alighted']],
'arise':[['arose'],['arisen']],
'awake':[['awoke'],['awoken']],
'babysit':[['babysat'],['babysat']],
'backlight':[['backlit', 'backlighted'],['backlit', 'backlighted']],
'backslide':[['backslid', 'backslided'],['backslidden', 'backslid', 'backslided']],
'be':[['was', 'were'],['been']],
'bear':[['bore'],['borne', 'born']],
'beat':[['beat'],['beaten', 'beat']],
'become':[['became'],['become']],
'bedo':[['bedid'],['bedone']],
'bedraw':[['bedrew'],['bedrawn']],
'bedream':[['bedreamed', 'bedreamt'],['bedreamed', 'bedreamt']],
'bedrive':[['bedrove'],['bedriven']],
'bedwell':[['bedwelt', 'bedwelled'],['bedwelt', 'bedwelled']],
'befall':[['befell'],['befallen']],
'befight':[['befought'],['befought']],
'begin':[['began'],['begun']],
'behear':[['beheard'],['beheard']],
'behold':[['beheld'],['beheld']],
'beken':[['bekenned', 'bekent'],['bekenned', 'bekent']],
'beknit':[['beknit', 'beknitted'],['beknit', 'beknitted']],
'belay':[['belaid'],['belaid']],
'beleap':[['beleaped', 'beleapt'],['beleaped', 'beleapt']],
'beleave':[['beleft'],['beleft']],
'bend':[['bent'],['bent']],
'bequeath':[['bequeathed', 'bequethed', 'bequoth', 'bequod'],['bequeathed', 'bequethed', 'bequoth', 'bequethen']],
'bereave':[['bereaved', 'bereft'],['bereaved', 'bereft']],
'beseech':[['beseeched'],['beseeched']],
'beseek':[['besought'],['besought']],
'beset':[['beset'],['beset']],
'bespeak':[['bespoke'],['bespoken']],
'bestrew':[['bestrewed'],['bestrewn', 'bestrewed']],
'bestride':[['bestrode'],['bestridden']],
'bet':[['bet', 'betted'],['bet', 'betted']],
'betake':[['betook'],['betaken']],
'betee':[['beteed', 'betow'],['beteed', 'betown']],
'betide':[['betided'],['betided']],
'beware':[[],[]],
'bid':[['bid'],['bid']],
'bide':[['bided', 'bode'],['bided', 'bidden']],
'bind':[['bound'],['bound']],
'bite':[['bit'],['bitten']],
'bleed':[['bled'],['bled']],
'blend':[['blended'],['blended']],
'bless':[['blessed'],['blessed']],
'blow':[['blew'],['blown']],
'bottle-feed':[['bottle-fed'],['bottle-fed']],
'break':[['broke'],['broken']],
'breastfeed':[['breastfed'],['breastfed']],
'breed':[['bred'],['bred']],
'bring':[['brought'],['brought']],
'broadcast':[['broadcast', 'broadcasted'],['broadcast', 'broadcasted']],
'browbeat':[['browbeat'],['browbeaten', 'browbeat']],
'build':[['built'],['built']],
'burn':[['burned', 'burnt'],['burned', 'burnt']],
'burst':[['burst'],['burst']],
'bust':[['busted', 'bust'],['busted', 'bust']],
'buy':[['bought'],['bought']],
'can':[['could'],[]],
'cast':[['cast'],['cast']],
'catch':[['caught'],['caught']],
'chide':[['chided', 'chid'],['chided', 'chid', 'chidden']],
'choose':[['chose'],['chosen']],
'clad':[['clad', 'cladded'],['clad', 'cladded']],
'clap':[['clapped'],['clapped']],
'clearcut':[['clearcut'],['clearcut']],
'cleave':[['cleft', 'clove', 'cleaved'],['cleft', 'cloven', 'cleaved']],
'cling':[['clung'],['clung']],
'clothe':[['clad', 'clothed'],['clad', 'clothed']],
'comb':[['combed'],['combed', 'kempt']],
'come':[['came'],['come', 'comen']],
'cost':[['cost', 'costed'],['cost', 'costed']],
'cowrite':[['cowrote'],['cowritten']],
'creep':[['crept', 'creeped'],['crept', 'creeped']],
'crosscut':[['crosscut'],['crosscut']],
'crow':[['crowed', 'crew'],['crowed']],
'cut':[['cut'],['cut']],
'dare':[['dared'],['dared']],
'deal':[['dealt'],['dealt']],
'dig':[['dug'],['dug']],
'dive':[['dived', 'dove'],['dived', 'dove']],
'do':[['did'],['done']],
'dow':[['dowed', 'dought'],['dowed', 'dought']],
'downcast':[['downcast', 'downcasted'],['downcast', 'downcasted']],
'downdraw':[['downdrew'],['downdrawn']],
'drag':[['dragged'],['dragged']],
'draw':[['drew'],['drawn']],
'dream':[['dreamed', 'dreamt'],['dreamed', 'dreamt']],
'dress':[['dressed'],['dressed']],
'drink':[['drank'],['drunk']],
'drive':[['drove'],['driven']],
'dwell':[['dwelt', 'dwelled'],['dwelt', 'dwelled']],
'earn':[['earned', 'earnt'],['earned', 'earnt']],
'eat':[['ate'],['eaten']],
'fall':[['fell'],['fallen']],
'feed':[['fed'],['fed']],
'feel':[['felt'],['felt']],
'fight':[['fought'],['fought']],
'find':[['found'],['found']],
'fit':[['fitted', 'fit'],['fitted', 'fit']],
'flee':[['fled'],['fled']],
'fling':[['flung'],['flung']],
'fly':[['flew'],['flown']],
'forbear':[['forbore'],['forborne', 'forborn']],
'forbid':[['forbid', 'forbade', 'forbad'],['forbidden']],
'force-feed':[['force-fed'],['force-fed']],
'forecast':[['forecast', 'forecasted'],['forecast', 'forecasted']],
'forefeel':[['forefelt'],['forefelt']],
'forego':[['forewent'],['foregone']],
'forehear':[['foreheard'],['foreheard']],
'foreken':[['forekenned', 'forekent'],['forekenned', 'forekent']],
'foreknow':[['foreknew'],['foreknown']],
'foresee':[['foresaw'],['foreseen']],
'foreshow':[['foreshowed'],['foreshown', 'foreshowed']],
'foretell':[['foretold'],['foretold']],
'forget':[['forgot'],['forgotten']],
'forgive':[['forgave'],['forgiven']],
'forgo':[['forwent'],['forgone']],
'forsake':[['forsook'],['forsaken']],
'forstand':[['forstood'],['forstood']],
'forswear':[['forswore'],['forsworn']],
'fortee':[['forteed', 'fortow'],['forteed', 'fortown']],
'forthcome':[['forthcame'],['forthcome']],
'forthleap':[['forthleaped', 'forthleapt'],['forthleaped', 'forthleapt']],
'forthtell':[['forthtold'],['forthtold']],
'freeze':[['froze'],['frozen']],
'fret':[['fretted', 'frate'],['fretted', 'fretten']],
'frostbite':[['frostbit'],['frostbitten']],
'get':[['got'],['got', 'gotten']],
'ghostwrite':[['ghostwrote'],['ghostwritten']],
'gild':[['gilded', 'gilt'],['gilded', 'gilt']],
'gird':[['girded'],['girded']],
'give':[['gave'],['given']],
'go':[['went'],['gone']],
'green-light':[['green-lit', 'green-lighted'],['green-lit', 'green-lighted']],
'grind':[['ground', 'grinded'],['ground', 'grinded']],
'grow':[['grew'],['grown']],
'hamstring':[['hamstrung'],['hamstrung']],
'hand-feed':[['hand-fed'],['hand-fed']],
'hand-knit':[['hand-knit', 'hand-knitted'],['hand-knit', 'hand-knitted']],
'handset':[['handset'],['handset']],
'handsew':[['handsewed'],['handsewn', 'handsewed']],
'handspring':[['handsprang', 'handsprung'],['handsprung']],
'handwrite':[['handwrote'],['handwritten']],
'hang':[['hung', 'hanged'],['hung', 'hanged']],
'have':[['had'],['had']],
'hear':[['heard'],['heard']],
'heave':[['heaved'],['heaved']],
'help':[['helped'],['helped']],
'hew':[['hewed'],['hewed', 'hewn']],
'hide':[['hid'],['hidden']],
'hit':[['hit'],['hit']],
'hoist':[['hoisted', 'hoist'],['hoisted', 'hoist']],
'hold':[['held'],['held']],
'housesit':[['housesat'],['housesat']],
'hurt':[['hurt'],['hurt']],
'inbreed':[['inbred'],['inbred']],
'inhold':[['inheld'],['inheld']],
'inlay':[['inlaid'],['inlaid']],
'inlead':[['inled'],['inled']],
'input':[['input', 'inputted'],['input', 'inputted']],
'inset':[['inset', 'insetted'],['inset', 'insetted']],
'intake':[['intook'],['intaken']],
'interbreed':[['interbred'],['interbred']],
'intercut':[['intercut'],['intercut']],
'interlay':[['interlaid'],['interlaid']],
'interweave':[['interwove', 'interweaved'],['interwoven', 'interweaved']],
'keep':[['kept'],['kept']],
'ken':[['kenned', 'kent'],['kenned', 'kent']],
'kneel':[['knelt', 'kneeled'],['knelt', 'kneeled']],
'knit':[['knit', 'knitted'],['knit', 'knitted']],
'know':[['knew'],['known']],
'lade':[['laded'],['laden', 'laded']],
'laugh':[['laughed'],['laughed']],
'lay':[['laid'],['laid']],
'lead':[['led'],['led']],
'lean':[['leaned', 'leant'],['leaned', 'leant']],
'leap':[['leaped', 'leapt'],['leaped', 'leapt']],
'learn':[['learned', 'learnt'],['learned', 'learnt']],
'leave':[['left'],['left']],
'lend':[['lent'],['lent']],
'let':[['let'],['let']],
'lie':[['lay'],['lain']],
'light':[['lit', 'lighted'],['lit', 'lighted']],
'lipread':[['lipread'],['lipread']],
'lose':[['lost'],['lost']],
'make':[['made'],['made']],
'may':[['might'],[]],
'mean':[['meant'],['meant']],
'meet':[['met'],['met']],
'melt':[['melted'],['melted', 'molten']],
'misbecome':[['misbecame'],['misbecome']],
'misbeget':[['misbegot'],['misbegotten', 'misbegot']],
'miscast':[['miscast'],['miscast']],
'mischoose':[['mischose'],['mischosen']],
'misdeal':[['misdealt'],['misdealt']],
'misdo':[['misdid'],['misdone']],
'misfeed':[['misfed'],['misfed']],
'misfit':[['misfitted', 'misfit'],['misfitted', 'misfit']],
'misgive':[['misgave'],['misgiven']],
'mishear':[['misheard'],['misheard']],
'mishit':[['mishit'],['mishit']],
'mishold':[['misheld'],['misheld']],
'miskeep':[['miskept'],['miskept']],
'misken':[['miskenned', 'miskent'],['miskenned', 'miskent']],
'misknow':[['misknew'],['misknown']],
'mislay':[['mislaid'],['mislaid']],
'mislead':[['misled'],['misled']],
'mislearn':[['mislearned', 'mislearnt'],['mislearned', 'mislearnt']],
'misread':[['misread'],['misread']],
'missay':[['missaid'],['missaid']],
'missee':[['missaw'],['misseen']],
'missend':[['missent'],['missent']],
'misset':[['misset'],['misset']],
'misshape':[['misshaped'],['misshaped']],
'misshoot':[['misshot'],['misshot']],
'misspeak':[['misspoke'],['misspoken']],
'misspell':[['misspelled', 'misspelt'],['misspelled', 'misspelt']],
'misspend':[['misspent'],['misspent']],
'mistake':[['mistook'],['mistaken']],
'mistell':[['mistold'],['mistold']],
'misthrow':[['misthrew'],['misthrown']],
'misunderstand':[['misunderstood'],['misunderstood']],
'miswed':[['miswed', 'miswedded'],['miswed', 'miswedded']],
'miswrite':[['miswrote'],['miswritten']],
'mix':[['mixed'],['mixed']],
'mow':[['mowed'],['mowed', 'mown']],
'must':[[],[]],
'need':[['needed'],['needed']],
'offlead':[['offled'],['offled']],
'offset':[['offset', 'offsetted'],['offset', 'offsetted']],
'onlay':[['onlaid'],['onlaid']],
'onlead':[['onled'],['onled']],
'ought':[[],[]],
'outbid':[['outbid'],['outbid', 'outbidden']],
'outbreak':[['outbroke'],['outbroken']],
'outdo':[['outdid'],['outdone']],
'outdraw':[['outdrew'],['outdrawn']],
'outdrink':[['outdrank'],['outdrunk']],
'outdwell':[['outdwelt', 'outdwelled'],['outdwelt', 'outdwelled']],
'outeat':[['outate'],['outeaten']],
'outfall':[['outfell'],['outfallen']],
'outfight':[['outfought'],['outfought']],
'outfly':[['outflew'],['outflown']],
'outgrow':[['outgrew'],['outgrown']],
'outhear':[['outheard'],['outheard']],
'outken':[['outkenned', 'outkent'],['outkenned', 'outkent']],
'outlay':[['outlaid'],['outlaid']],
'outlead':[['outled'],['outled']],
'outleap':[['outleaped', 'outleapt'],['outleaped', 'outleapt']],
'output':[['output', 'outputted'],['output', 'outputted']],
'outride':[['outrode'],['outridden']],
'outrun':[['outran'],['outrun']],
'outsell':[['outsold'],['outsold']],
'outshine':[['outshone', 'outshined'],['outshone', 'outshined']],
'outspend':[['outspent'],['outspent']],
'outspin':[['outspun'],['outspun']],
'outspread':[['outspread'],['outspread']],
'outstride':[['outstrode'],['outstridden']],
'outstrive':[['outstrove'],['outstriven']],
'outswear':[['outswore'],['outsworn']],
'outswim':[['outswam'],['outswum']],
'outthink':[['outthought'],['outthought']],
'outthrow':[['outthrew'],['outthrown']],
'outthrust':[['outthrusted'],['outthrusted']],
'outwear':[['outweared', 'outwore'],['outweared', 'outworn']],
'overbear':[['overbore'],['overborne', 'overborn']],
'overbeat':[['overbeat'],['overbeaten', 'overbeat']],
'overbend':[['overbent'],['overbent']],
'overbid':[['overbid'],['overbid']],
'overblow':[['overblew'],['overblown']],
'overbreed':[['overbred'],['overbred']],
'overbuild':[['overbuilt'],['overbuilt']],
'overbuy':[['overbought'],['overbought']],
'overcast':[['overcast'],['overcast']],
'overclothe':[['overclad', 'overclothed'],['overclad', 'overclothed']],
'overcome':[['overcame'],['overcome', 'overcomen']],
'overdo':[['overdid'],['overdone']],
'overdraw':[['overdrew'],['overdrawn']],
'overdrink':[['overdrank'],['overdrunk']],
'overdrive':[['overdrove'],['overdriven']],
'overeat':[['overate'],['overeaten']],
'overfeed':[['overfed'],['overfed']],
'overfly':[['overflew'],['overflown']],
'overgive':[['overgave'],['overgiven']],
'overgrow':[['overgrew'],['overgrown']],
'overhang':[['overhung', 'overhanged'],['overhung', 'overhanged']],
'overhear':[['overheard'],['overheard']],
'overhit':[['overhit'],['overhit']],
'overkeep':[['overkept'],['overkept']],
'overlade':[['overladed'],['overladen', 'overladed']],
'overlay':[['overlaid', 'overlayed'],['overlaid', 'overlayed']],
'overlead':[['overled'],['overled']],
'overleap':[['overleaped', 'overleapt'],['overleaped', 'overleapt']],
'overlearn':[['overlearned', 'overlearnt'],['overlearned', 'overlearnt']],
'overleave':[['overleft'],['overleft']],
'overlie':[['overlay'],['overlain']],
'overpay':[['overpaid'],['overpaid']],
'override':[['overrode'],['overridden']],
'overrun':[['overran'],['overrun']],
'oversee':[['oversaw'],['overseen']],
'oversell':[['oversold'],['oversold']],
'overset':[['overset'],['overset']],
'oversew':[['oversewed'],['oversewn', 'oversewed']],
'overshake':[['overshook'],['overshaken']],
'overshine':[['overshone', 'overshined'],['overshone', 'overshined']],
'overshoot':[['overshot'],['overshot']],
'overshrink':[['overshrank', 'overshrunk'],['overshrunk', 'overshrunken']],
'oversleep':[['overslept'],['overslept']],
'overslide':[['overslid'],['overslid', 'overslidden']],
'overspend':[['overspent'],['overspent']],
'overspill':[['overspilled', 'overspilt'],['overspilled', 'overspilt']],
'overspread':[['overspread'],['overspread']],
'overstand':[['overstood'],['overstood']],
'overstrew':[['overstrewed'],['overstrewn', 'overstrewed']],
'overstride':[['overstrode'],['overstrode', 'overstridden']],
'overstrike':[['overstruck'],['overstruck', 'overstricken']],
'overstring':[['overstrung'],['overstrung']],
'overstrive':[['overstrove'],['overstriven']],
'overswing':[['overswang', 'overswung'],['overswung']],
'overtake':[['overtook'],['overtaken']],
'overthrow':[['overthrew'],['overthrown']],
'overwear':[['overweared', 'overwore'],['overweared', 'overworn']],
'overwet':[['overwet', 'overwetted'],['overwet', 'overwetted']],
'overwork':[['overworked', 'overwrought'],['overworked', 'overwrought']],
'overwrite':[['overwrote'],['overwritten']],
'partake':[['partook'],['partaken']],
'pay':[['paid'],['paid']],
'pen':[['penned', 'pent'],['penned', 'pent']],
'plead':[['pleaded', 'pled', 'plead'],['pleaded', 'pled', 'plead']],
'podcast':[['podcast', 'podcasted'],['podcast', 'podcasted']],
'precast':[['precast'],['precast']],
'prepay':[['prepaid'],['prepayed', 'prepaid']],
'preset':[['preset'],['preset']],
'proofread':[['proofread'],['proofread']],
'prove':[['proved'],['proved', 'proven']],
'put':[['put'],['put']],
'quick-freeze':[['quick-froze'],['quick-frozen']],
'quit':[['quit', 'quitted'],['quit', 'quitted']],
're-lay':[['re-laid'],['re-laid']],
'reach':[['reached'],['reached']],
'read':[['read'],['read']],
'rebid':[['rebid'],['rebid']],
'rebreak':[['rebroke'],['rebroken']],
'rebuild':[['rebuilt'],['rebuilt']],
'recast':[['recast'],['recast']],
'recut':[['recut'],['recut']],
'redeal':[['redealt'],['redealt']],
'redo':[['redid'],['redone']],
'redraw':[['redrew'],['redrawn']],
'refind':[['refound'],['refound']],
'refreeze':[['refroze'],['refrozen']],
'regrow':[['regrew'],['regrown']],
'rehear':[['reheard'],['reheard']],
'relearn':[['relearned', 'relearnt'],['relearned', 'relearnt']],
'relight':[['relit', 'relighted'],['relit', 'relighted']],
'remake':[['remade'],['remade']],
'rend':[['rent', 'rended'],['rent', 'rended']],
'repay':[['repaid'],['repaid']],
'reprove':[['reproved'],['reproved', 'reproven']],
'reread':[['reread'],['reread']],
'rerun':[['reran'],['rerun']],
'resell':[['resold'],['resold']],
'resend':[['resent'],['resent']],
'reset':[['reset'],['reset']],
'reshoe':[['reshod', 'reshoed'],['reshodden', 'reshod', 'reshoed']],
'reshoot':[['reshot'],['reshot']],
'reshow':[['reshowed'],['reshown', 'reshowed']],
'reshut':[['reshut'],['reshut']],
'resing':[['resang'],['resung']],
'resit':[['resat'],['resat']],
'retake':[['retook'],['retaken']],
'retell':[['retold'],['retold']],
'rethink':[['rethought'],['rethought']],
'retread':[['retrod'],['retrodden']],
'rewed':[['rewed', 'rewedded'],['rewed', 'rewedded']],
'rewind':[['rewound'],['rewound']],
'rewrite':[['rewrote'],['rewritten']],
'rid':[['rid', 'ridded'],['rid', 'ridden', 'ridded']],
'ride':[['rode'],['ridden']],
'ring':[['rang'],['rung']],
'rise':[['rose'],['risen']],
'rive':[['rived', 'rove'],['rived', 'riven']],
'run':[['ran'],['run']],
'saw':[['sawed'],['sawed', 'sawn']],
'say':[['said'],['said']],
'see':[['saw'],['seen']],
'seek':[['sought'],['sought']],
'seethe':[['seethed'],['seethed']],
'self-feed':[['self-fed'],['self-fed']],
'sell':[['sold'],['sold']],
'send':[['sent'],['sent']],
'set':[['set'],['set']],
'sew':[['sewed'],['sewn', 'sewed']],
'shake':[['shook'],['shaken']],
'shall':[['should'],[]],
'shape':[['shaped'],['shaped']],
'shave':[['shaved'],['shaved', 'shaven']],
'shear':[['sheared', 'shore'],['shorn', 'sheared']],
'shed':[['shed'],['shed']],
'shine':[['shone', 'shined'],['shone', 'shined']],
'shit':[['shit', 'shitted', 'shat'],['shit', 'shitted', 'shat']],
'shite':[['shited', 'shit', 'shat'],['shited', 'shitten']],
'shoe':[['shod', 'shoed'],['shodden', 'shod', 'shoed']],
'shoot':[['shot'],['shot']],
'show':[['showed'],['shown']],
'shrink':[['shrank', 'shrunk'],['shrunk', 'shrunken']],
'shut':[['shut'],['shut']],
'sight-read':[['sight-read'],['sight-read']],
'sightsee':[['sightsaw'],['sightseen']],
'simulcast':[['simulcast', 'simulcasted'],['simulcast', 'simulcasted']],
'sing':[['sang'],['sung']],
'sink':[['sank', 'sunk'],['sunk', 'sunken']],
'sit':[['sat'],['sat']],
'slay':[['slew', 'slayed'],['slain', 'slayed']],
'sleep':[['slept'],['slept']],
'slide':[['slid'],['slid', 'slidden']],
'sling':[['slung'],['slung']],
'slink':[['slunk', 'slinked', 'slank'],['slunk', 'slinked', 'slank']],
'slip':[['slipped'],['slipped']],
'slit':[['slit'],['slit', 'slitten']],
'smell':[['smelled', 'smelt'],['smelled', 'smelt']],
'smite':[['smote'],['smitten', 'smited']],
'sneak':[['sneaked', 'snuck'],['sneaked', 'snuck']],
'soothsay':[['soothsaid'],['soothsaid']],
'sow':[['sowed'],['sown', 'sowed']],
'speak':[['spoke'],['spoken']],
'speed':[['sped', 'speeded'],['sped', 'speeded']],
'spell':[['spelled', 'spelt'],['spelled', 'spelt']],
'spend':[['spent'],['spent']],
'spill':[['spilled', 'spilt'],['spilled', 'spilt']],
'spin':[['spun'],['spun']],
'spit':[['spat', 'spit'],['spat', 'spit']],
'split':[['split'],['split']],
'spoil':[['spoiled', 'spoilt'],['spoiled', 'spoilt']],
'spoon-feed':[['spoon-fed'],['spoon-fed']],
'spread':[['spread'],['spread']],
'spring':[['sprang', 'sprung'],['sprung']],
'stand':[['stood'],['stood']],
'starve':[['starved'],['starved']],
'stave':[['stove', 'staved'],['stove', 'staved']],
'stay':[['stayed'],['stayed']],
'steal':[['stole'],['stolen']],
'stick':[['stuck'],['stuck']],
'sting':[['stung'],['stung']],
'stink':[['stank', 'stunk'],['stunk']],
'stretch':[['stretched'],['stretched']],
'strew':[['strewed'],['strewn', 'strewed']],
'stride':[['strode'],['stridden']],
'strike':[['struck'],['struck', 'stricken']],
'string':[['strung'],['strung']],
'strip':[['stripped', 'stript'],['stripped', 'stript']],
'strive':[['strove', 'strived'],['striven', 'strived']],
'sublet':[['sublet'],['sublet']],
'sunburn':[['sunburned', 'sunburnt'],['sunburned', 'sunburnt']],
'swear':[['swore'],['sworn']],
'sweat':[['sweated', 'sweat'],['sweated', 'sweat']],
'sweep':[['swept'],['swept']],
'swell':[['swelled'],['swollen', 'swelled']],
'swim':[['swam'],['swum']],
'swing':[['swang', 'swung'],['swung']],
'take':[['took'],['taken']],
'teach':[['taught'],['taught']],
'tear':[['tore'],['torn']],
'telecast':[['telecast', 'telecasted'],['telecast', 'telecasted']],
'tell':[['told'],['told']],
'test-drive':[['test-drove'],['test-driven']],
'test-fly':[['test-flew'],['test-flown']],
'think':[['thought'],['thought']],
'thrive':[['throve', 'thrived'],['thriven', 'thrived']],
'throw':[['threw'],['thrown']],
'thrust':[['thrust', 'thrusted'],['thrust', 'thrusted']],
'tread':[['trod'],['trodden', 'trod']],
'typecast':[['typecast', 'typecasted'],['typecast', 'typecasted']],
'unbend':[['unbent'],['unbent']],
'unbind':[['unbound'],['unbound']],
'unclothe':[['unclad', 'unclothed'],['unclad', 'unclothed']],
'underbear':[['underbore'],['underborne', 'underborn']],
'underbet':[['underbet'],['underbet']],
'underbid':[['underbid'],['underbid']],
'underbind':[['underbound'],['underbound']],
'underbuild':[['underbuilt'],['underbuilt']],
'underbuy':[['underbought'],['underbought']],
'undercast':[['undercast'],['undercast']],
'underclothe':[['underclad', 'underclothed'],['underclad', 'underclothed']],
'undercut':[['undercut'],['undercut']],
'underdig':[['underdug'],['underdug']],
'underdo':[['underdid'],['underdone']],
'underdraw':[['underdrew'],['underdrawn']],
'undereat':[['underate'],['undereaten']],
'underfeed':[['underfed'],['underfed']],
'undergird':[['undergirded'],['undergirded']],
'undergo':[['underwent'],['undergone']],
'undergrow':[['undergrew'],['undergrown']],
'underhang':[['underhung', 'underhanged'],['underhung', 'underhanged']],
'underhit':[['underhit'],['underhit']],
'underkeep':[['underkept'],['underkept']],
'underlay':[['underlaid'],['underlaid']],
'underlead':[['underled'],['underled']],
'underlie':[['underlay'],['underlain']],
'underpay':[['underpaid'],['underpaid']],
'underrun':[['underran'],['underrun']],
'undersee':[['undersaw'],['underseen']],
'undersell':[['undersold'],['undersold']],
'undershoot':[['undershot'],['undershot']],
'undersleep':[['underslept'],['underslept']],
'underspread':[['underspread'],['underspread']],
'understand':[['understood'],['understood']],
'undertake':[['undertook'],['undertaken']],
'underthrow':[['underthrew'],['underthrown']],
'underwrite':[['underwrote'],['underwritten']],
'undo':[['undid'],['undone']],
'unfreeze':[['unfroze'],['unfrozen']],
'unhear':[['unheard'],['unheard']],
'unlay':[['unlaid'],['unlaid']],
'unlearn':[['unlearned', 'unlearnt'],['unlearned', 'unlearnt']],
'unmake':[['unmade'],['unmade']],
'unwind':[['unwound'],['unwound']],
'upcast':[['upcast', 'upcasted'],['upcast', 'upcasted']],
'updraw':[['updrew'],['updrawn']],
'upgrow':[['upgrew'],['upgrown']],
'uphang':[['uphung', 'uphanged'],['uphung', 'uphanged']],
'upheave':[['upheaved', 'uphove'],['upheaved']],
'uphold':[['upheld'],['upheld']],
'uprise':[['uprose'],['uprisen']],
'upsell':[['upsold'],['upsold']],
'upset':[['upset'],['upset']],
'upstand':[['upstood'],['upstood']],
'upsweep':[['upswept'],['upswept']],
'upswell':[['upswelled'],['upswollen', 'upswelled']],
'uptear':[['uptore'],['uptorn']],
'upthrow':[['upthrew'],['upthrown']],
'vex':[['vexed'],['vexed']],
'wake':[['woke'],['woken']],
'wax':[['waxed'],['waxed']],
'waylay':[['waylaid'],['waylaid']],
'wear':[['weared', 'wore'],['weared', 'worn']],
'weave':[['wove', 'weaved'],['woven', 'weaved']],
'webcast':[['webcast'],['webcast']],
'wed':[['wed', 'wedded'],['wed', 'wedded']],
'weep':[['wept', 'weeped'],['wept', 'weeped']],
'wend':[['wended'],['wended']],
'wet':[['wet', 'wetted'],['wet', 'wetted']],
'will':[['would'],[]],
'win':[['won'],['won']],
'wind':[['wound'],['wound']],
'withdraw':[['withdrew'],['withdrawn']],
'withhold':[['withheld'],['withheld']],
'withstand':[['withstood'],['withstood']],
'work':[['worked'],['worked']],
'wreak':[['wreaked', 'wrought'],['wreaked', 'wrought']],
'wring':[['wrang', 'wrung'],['wrung']],
'write':[['wrote'],['written']],
'writhe':[['writhed'],['writhed']],
'zinc':[['zinced', 'zinked', 'zincked'],['zinced', 'zinked', 'zincked']],
}
