# The following dictionary of irregular verbs was constructed with data
# scraped from this link:
#     'https://en.wikipedia.org/wiki/List_of_English_irregular_verbs'

# Verbs marked as archaic are omitted unless their Wiktionary entry
# indicates that they are actually NOT archaic. There are lots of discrepancies
# between Wiktionary and Wikipedia for these verbs. An attempt at resolving
# these has been performed by the associated scraping code.
#
# Each entry has the form:
#
#     base_form:[ [past tense (preterite) forms], [past participle forms]]

VERBS = {
    'abide':[['abided'],['abided']],
    'ache':[['ached'],['ached']],
    'alight':[['alit', 'alighted'],['alit', 'alighted']],
    'arise':[['arose'],['arisen']],
    'awake':[['awoke'],['awoken']],
    'babysit':[['babysat'],['babysat']],
    'backlight':[['backlit', 'backlighted'],['backlit', 'backlighted']],
    'backslide':[['backslid', 'backslided'],['backslidden', 'backslid', 'backslided']],
    'be':[['was', 'were'],['been']],
    'bear':[['bore'],['borne', 'born']],
    'beat':[['beat'],['beaten', 'beat']],
    'become':[['became'],['become']],
    'bedo':[['bedid'],['bedone']],
    'bedraw':[['bedrew'],['bedrawn']],
    'bedream':[['bedreamed', 'bedreamt'],['bedreamed', 'bedreamt']],
    'bedrive':[['bedrove'],['bedriven']],
    'bedwell':[['bedwelt', 'bedwelled'],['bedwelt', 'bedwelled']],
    'befall':[['befell'],['befallen']],
    'befight':[['befought'],['befought']],
    'begin':[['began'],['begun']],
    'behear':[['beheard'],['beheard']],
    'behold':[['beheld'],['beheld']],
    'beken':[['bekenned', 'bekent'],['bekenned', 'bekent']],
    'beknit':[['beknit', 'beknitted'],['beknit', 'beknitted']],
    'belay':[['belaid'],['belaid']],
    'beleap':[['beleaped', 'beleapt'],['beleaped', 'beleapt']],
    'beleave':[['beleft'],['beleft']],
    'bend':[['bent'],['bent']],
    'bequeath':[['bequeathed', 'bequethed', 'bequoth', 'bequod'],['bequeathed', 'bequethed', 'bequoth', 'bequethen']],
    'bereave':[['bereaved', 'bereft'],['bereaved', 'bereft']],
    'beseech':[['beseeched'],['beseeched']],
    'beseek':[['besought'],['besought']],
    'beset':[['beset'],['beset']],
    'bespeak':[['bespoke'],['bespoken']],
    'bestrew':[['bestrewed'],['bestrewn', 'bestrewed']],
    'bestride':[['bestrode'],['bestridden']],
    'bet':[['bet', 'betted'],['bet', 'betted']],
    'betake':[['betook'],['betaken']],
    'betee':[['beteed', 'betow'],['beteed', 'betown']],
    'betide':[['betided'],['betided']],
    'beware':[[],[]],
    'bid':[['bid'],['bid']],
    'bide':[['bided', 'bode'],['bided', 'bidden']],
    'bind':[['bound'],['bound']],
    'bite':[['bit'],['bitten']],
    'bleed':[['bled'],['bled']],
    'blend':[['blended'],['blended']],
    'bless':[['blessed'],['blessed']],
    'blow':[['blew'],['blown']],
    'bottle-feed':[['bottle-fed'],['bottle-fed']],
    'break':[['broke'],['broken']],
    'breastfeed':[['breastfed'],['breastfed']],
    'breed':[['bred'],['bred']],
    'bring':[['brought'],['brought']],
    'broadcast':[['broadcast', 'broadcasted'],['broadcast', 'broadcasted']],
    'browbeat':[['browbeat'],['browbeaten', 'browbeat']],
    'build':[['built'],['built']],
    'burn':[['burned', 'burnt'],['burned', 'burnt']],
    'burst':[['burst'],['burst']],
    'bust':[['busted', 'bust'],['busted', 'bust']],
    'buy':[['bought'],['bought']],
    'can':[['could'],[]],
    'cast':[['cast'],['cast']],
    'catch':[['caught'],['caught']],
    'chide':[['chided', 'chid'],['chided', 'chid', 'chidden']],
    'choose':[['chose'],['chosen']],
    'clad':[['clad', 'cladded'],['clad', 'cladded']],
    'clap':[['clapped'],['clapped']],
    'clearcut':[['clearcut'],['clearcut']],
    'cleave':[['cleft', 'clove', 'cleaved'],['cleft', 'cloven', 'cleaved']],
    'cling':[['clung'],['clung']],
    'clothe':[['clad', 'clothed'],['clad', 'clothed']],
    'comb':[['combed'],['combed', 'kempt']],
    'come':[['came'],['come', 'comen']],
    'cost':[['cost', 'costed'],['cost', 'costed']],
    'cowrite':[['cowrote'],['cowritten']],
    'creep':[['crept', 'creeped'],['crept', 'creeped']],
    'crosscut':[['crosscut'],['crosscut']],
    'crow':[['crowed', 'crew'],['crowed']],
    'cut':[['cut'],['cut']],
    'dare':[['dared'],['dared']],
    'deal':[['dealt'],['dealt']],
    'dig':[['dug'],['dug']],
    'dive':[['dived', 'dove'],['dived', 'dove']],
    'do':[['did'],['done']],
    'dow':[['dowed', 'dought'],['dowed', 'dought']],
    'downcast':[['downcast', 'downcasted'],['downcast', 'downcasted']],
    'downdraw':[['downdrew'],['downdrawn']],
    'drag':[['dragged'],['dragged']],
    'draw':[['drew'],['drawn']],
    'dream':[['dreamed', 'dreamt'],['dreamed', 'dreamt']],
    'dress':[['dressed'],['dressed']],
    'drink':[['drank'],['drunk']],
    'drive':[['drove'],['driven']],
    'dwell':[['dwelt', 'dwelled'],['dwelt', 'dwelled']],
    'earn':[['earned', 'earnt'],['earned', 'earnt']],
    'eat':[['ate'],['eaten']],
    'fall':[['fell'],['fallen']],
    'feed':[['fed'],['fed']],
    'feel':[['felt'],['felt']],
    'fight':[['fought'],['fought']],
    'find':[['found'],['found']],
    'fit':[['fitted', 'fit'],['fitted', 'fit']],
    'flee':[['fled'],['fled']],
    'fling':[['flung'],['flung']],
    'fly':[['flew'],['flown']],
    'forbear':[['forbore'],['forborne', 'forborn']],
    'forbid':[['forbid', 'forbade', 'forbad'],['forbidden']],
    'force-feed':[['force-fed'],['force-fed']],
    'forecast':[['forecast', 'forecasted'],['forecast', 'forecasted']],
    'forefeel':[['forefelt'],['forefelt']],
    'forego':[['forewent'],['foregone']],
    'forehear':[['foreheard'],['foreheard']],
    'foreken':[['forekenned', 'forekent'],['forekenned', 'forekent']],
    'foreknow':[['foreknew'],['foreknown']],
    'foresee':[['foresaw'],['foreseen']],
    'foreshow':[['foreshowed'],['foreshown', 'foreshowed']],
    'foretell':[['foretold'],['foretold']],
    'forget':[['forgot'],['forgotten']],
    'forgive':[['forgave'],['forgiven']],
    'forgo':[['forwent'],['forgone']],
    'forsake':[['forsook'],['forsaken']],
    'forstand':[['forstood'],['forstood']],
    'forswear':[['forswore'],['forsworn']],
    'fortee':[['forteed', 'fortow'],['forteed', 'fortown']],
    'forthcome':[['forthcame'],['forthcome']],
    'forthleap':[['forthleaped', 'forthleapt'],['forthleaped', 'forthleapt']],
    'forthtell':[['forthtold'],['forthtold']],
    'freeze':[['froze'],['frozen']],
    'fret':[['fretted', 'frate'],['fretted', 'fretten']],
    'frostbite':[['frostbit'],['frostbitten']],
    'get':[['got'],['got', 'gotten']],
    'ghostwrite':[['ghostwrote'],['ghostwritten']],
    'gild':[['gilded', 'gilt'],['gilded', 'gilt']],
    'gird':[['girded'],['girded']],
    'give':[['gave'],['given']],
    'go':[['went'],['gone']],
    'green-light':[['green-lit', 'green-lighted'],['green-lit', 'green-lighted']],
    'grind':[['ground', 'grinded'],['ground', 'grinded']],
    'grow':[['grew'],['grown']],
    'hamstring':[['hamstrung'],['hamstrung']],
    'hand-feed':[['hand-fed'],['hand-fed']],
    'hand-knit':[['hand-knit', 'hand-knitted'],['hand-knit', 'hand-knitted']],
    'handset':[['handset'],['handset']],
    'handsew':[['handsewed'],['handsewn', 'handsewed']],
    'handspring':[['handsprang', 'handsprung'],['handsprung']],
    'handwrite':[['handwrote'],['handwritten']],
    'hang':[['hung', 'hanged'],['hung', 'hanged']],
    'have':[['had'],['had']],
    'hear':[['heard'],['heard']],
    'heave':[['heaved'],['heaved']],
    'help':[['helped'],['helped']],
    'hew':[['hewed'],['hewed', 'hewn']],
    'hide':[['hid'],['hidden']],
    'hit':[['hit'],['hit']],
    'hoist':[['hoisted', 'hoist'],['hoisted', 'hoist']],
    'hold':[['held'],['held']],
    'housesit':[['housesat'],['housesat']],
    'hurt':[['hurt'],['hurt']],
    'inbreed':[['inbred'],['inbred']],
    'inhold':[['inheld'],['inheld']],
    'inlay':[['inlaid'],['inlaid']],
    'inlead':[['inled'],['inled']],
    'input':[['input', 'inputted'],['input', 'inputted']],
    'inset':[['inset', 'insetted'],['inset', 'insetted']],
    'intake':[['intook'],['intaken']],
    'interbreed':[['interbred'],['interbred']],
    'intercut':[['intercut'],['intercut']],
    'interlay':[['interlaid'],['interlaid']],
    'interweave':[['interwove', 'interweaved'],['interwoven', 'interweaved']],
    'keep':[['kept'],['kept']],
    'ken':[['kenned', 'kent'],['kenned', 'kent']],
    'kneel':[['knelt', 'kneeled'],['knelt', 'kneeled']],
    'knit':[['knit', 'knitted'],['knit', 'knitted']],
    'know':[['knew'],['known']],
    'lade':[['laded'],['laden', 'laded']],
    'laugh':[['laughed'],['laughed']],
    'lay':[['laid'],['laid']],
    'lead':[['led'],['led']],
    'lean':[['leaned', 'leant'],['leaned', 'leant']],
    'leap':[['leaped', 'leapt'],['leaped', 'leapt']],
    'learn':[['learned', 'learnt'],['learned', 'learnt']],
    'leave':[['left'],['left']],
    'lend':[['lent'],['lent']],
    'let':[['let'],['let']],
    'lie':[['lay'],['lain']],
    'light':[['lit', 'lighted'],['lit', 'lighted']],
    'lipread':[['lipread'],['lipread']],
    'lose':[['lost'],['lost']],
    'make':[['made'],['made']],
    'may':[['might'],[]],
    'mean':[['meant'],['meant']],
    'meet':[['met'],['met']],
    'melt':[['melted'],['melted', 'molten']],
    'misbecome':[['misbecame'],['misbecome']],
    'misbeget':[['misbegot'],['misbegotten', 'misbegot']],
    'miscast':[['miscast'],['miscast']],
    'mischoose':[['mischose'],['mischosen']],
    'misdeal':[['misdealt'],['misdealt']],
    'misdo':[['misdid'],['misdone']],
    'misfeed':[['misfed'],['misfed']],
    'misfit':[['misfitted', 'misfit'],['misfitted', 'misfit']],
    'misgive':[['misgave'],['misgiven']],
    'mishear':[['misheard'],['misheard']],
    'mishit':[['mishit'],['mishit']],
    'mishold':[['misheld'],['misheld']],
    'miskeep':[['miskept'],['miskept']],
    'misken':[['miskenned', 'miskent'],['miskenned', 'miskent']],
    'misknow':[['misknew'],['misknown']],
    'mislay':[['mislaid'],['mislaid']],
    'mislead':[['misled'],['misled']],
    'mislearn':[['mislearned', 'mislearnt'],['mislearned', 'mislearnt']],
    'misread':[['misread'],['misread']],
    'missay':[['missaid'],['missaid']],
    'missee':[['missaw'],['misseen']],
    'missend':[['missent'],['missent']],
    'misset':[['misset'],['misset']],
    'misshape':[['misshaped'],['misshaped']],
    'misshoot':[['misshot'],['misshot']],
    'misspeak':[['misspoke'],['misspoken']],
    'misspell':[['misspelled', 'misspelt'],['misspelled', 'misspelt']],
    'misspend':[['misspent'],['misspent']],
    'mistake':[['mistook'],['mistaken']],
    'mistell':[['mistold'],['mistold']],
    'misthrow':[['misthrew'],['misthrown']],
    'misunderstand':[['misunderstood'],['misunderstood']],
    'miswed':[['miswed', 'miswedded'],['miswed', 'miswedded']],
    'miswrite':[['miswrote'],['miswritten']],
    'mix':[['mixed'],['mixed']],
    'mow':[['mowed'],['mowed', 'mown']],
    'must':[[],[]],
    'need':[['needed'],['needed']],
    'offlead':[['offled'],['offled']],
    'offset':[['offset', 'offsetted'],['offset', 'offsetted']],
    'onlay':[['onlaid'],['onlaid']],
    'onlead':[['onled'],['onled']],
    'ought':[[],[]],
    'outbid':[['outbid'],['outbid', 'outbidden']],
    'outbreak':[['outbroke'],['outbroken']],
    'outdo':[['outdid'],['outdone']],
    'outdraw':[['outdrew'],['outdrawn']],
    'outdrink':[['outdrank'],['outdrunk']],
    'outdwell':[['outdwelt', 'outdwelled'],['outdwelt', 'outdwelled']],
    'outeat':[['outate'],['outeaten']],
    'outfall':[['outfell'],['outfallen']],
    'outfight':[['outfought'],['outfought']],
    'outfly':[['outflew'],['outflown']],
    'outgrow':[['outgrew'],['outgrown']],
    'outhear':[['outheard'],['outheard']],
    'outken':[['outkenned', 'outkent'],['outkenned', 'outkent']],
    'outlay':[['outlaid'],['outlaid']],
    'outlead':[['outled'],['outled']],
    'outleap':[['outleaped', 'outleapt'],['outleaped', 'outleapt']],
    'output':[['output', 'outputted'],['output', 'outputted']],
    'outride':[['outrode'],['outridden']],
    'outrun':[['outran'],['outrun']],
    'outsell':[['outsold'],['outsold']],
    'outshine':[['outshone', 'outshined'],['outshone', 'outshined']],
    'outspend':[['outspent'],['outspent']],
    'outspin':[['outspun'],['outspun']],
    'outspread':[['outspread'],['outspread']],
    'outstride':[['outstrode'],['outstridden']],
    'outstrive':[['outstrove'],['outstriven']],
    'outswear':[['outswore'],['outsworn']],
    'outswim':[['outswam'],['outswum']],
    'outthink':[['outthought'],['outthought']],
    'outthrow':[['outthrew'],['outthrown']],
    'outthrust':[['outthrusted'],['outthrusted']],
    'outwear':[['outweared', 'outwore'],['outweared', 'outworn']],
    'overbear':[['overbore'],['overborne', 'overborn']],
    'overbeat':[['overbeat'],['overbeaten', 'overbeat']],
    'overbend':[['overbent'],['overbent']],
    'overbid':[['overbid'],['overbid']],
    'overblow':[['overblew'],['overblown']],
    'overbreed':[['overbred'],['overbred']],
    'overbuild':[['overbuilt'],['overbuilt']],
    'overbuy':[['overbought'],['overbought']],
    'overcast':[['overcast'],['overcast']],
    'overclothe':[['overclad', 'overclothed'],['overclad', 'overclothed']],
    'overcome':[['overcame'],['overcome', 'overcomen']],
    'overdo':[['overdid'],['overdone']],
    'overdraw':[['overdrew'],['overdrawn']],
    'overdrink':[['overdrank'],['overdrunk']],
    'overdrive':[['overdrove'],['overdriven']],
    'overeat':[['overate'],['overeaten']],
    'overfeed':[['overfed'],['overfed']],
    'overfly':[['overflew'],['overflown']],
    'overgive':[['overgave'],['overgiven']],
    'overgrow':[['overgrew'],['overgrown']],
    'overhang':[['overhung', 'overhanged'],['overhung', 'overhanged']],
    'overhear':[['overheard'],['overheard']],
    'overhit':[['overhit'],['overhit']],
    'overkeep':[['overkept'],['overkept']],
    'overlade':[['overladed'],['overladen', 'overladed']],
    'overlay':[['overlaid', 'overlayed'],['overlaid', 'overlayed']],
    'overlead':[['overled'],['overled']],
    'overleap':[['overleaped', 'overleapt'],['overleaped', 'overleapt']],
    'overlearn':[['overlearned', 'overlearnt'],['overlearned', 'overlearnt']],
    'overleave':[['overleft'],['overleft']],
    'overlie':[['overlay'],['overlain']],
    'overpay':[['overpaid'],['overpaid']],
    'override':[['overrode'],['overridden']],
    'overrun':[['overran'],['overrun']],
    'oversee':[['oversaw'],['overseen']],
    'oversell':[['oversold'],['oversold']],
    'overset':[['overset'],['overset']],
    'oversew':[['oversewed'],['oversewn', 'oversewed']],
    'overshake':[['overshook'],['overshaken']],
    'overshine':[['overshone', 'overshined'],['overshone', 'overshined']],
    'overshoot':[['overshot'],['overshot']],
    'overshrink':[['overshrank', 'overshrunk'],['overshrunk', 'overshrunken']],
    'oversleep':[['overslept'],['overslept']],
    'overslide':[['overslid'],['overslid', 'overslidden']],
    'overspend':[['overspent'],['overspent']],
    'overspill':[['overspilled', 'overspilt'],['overspilled', 'overspilt']],
    'overspread':[['overspread'],['overspread']],
    'overstand':[['overstood'],['overstood']],
    'overstrew':[['overstrewed'],['overstrewn', 'overstrewed']],
    'overstride':[['overstrode'],['overstrode', 'overstridden']],
    'overstrike':[['overstruck'],['overstruck', 'overstricken']],
    'overstring':[['overstrung'],['overstrung']],
    'overstrive':[['overstrove'],['overstriven']],
    'overswing':[['overswang', 'overswung'],['overswung']],
    'overtake':[['overtook'],['overtaken']],
    'overthrow':[['overthrew'],['overthrown']],
    'overwear':[['overweared', 'overwore'],['overweared', 'overworn']],
    'overwet':[['overwet', 'overwetted'],['overwet', 'overwetted']],
    'overwork':[['overworked', 'overwrought'],['overworked', 'overwrought']],
    'overwrite':[['overwrote'],['overwritten']],
    'partake':[['partook'],['partaken']],
    'pay':[['paid'],['paid']],
    'pen':[['penned', 'pent'],['penned', 'pent']],
    'plead':[['pleaded', 'pled', 'plead'],['pleaded', 'pled', 'plead']],
    'podcast':[['podcast', 'podcasted'],['podcast', 'podcasted']],
    'precast':[['precast'],['precast']],
    'prepay':[['prepaid'],['prepayed', 'prepaid']],
    'preset':[['preset'],['preset']],
    'proofread':[['proofread'],['proofread']],
    'prove':[['proved'],['proved', 'proven']],
    'put':[['put'],['put']],
    'quick-freeze':[['quick-froze'],['quick-frozen']],
    'quit':[['quit', 'quitted'],['quit', 'quitted']],
    're-lay':[['re-laid'],['re-laid']],
    'reach':[['reached'],['reached']],
    'read':[['read'],['read']],
    'rebid':[['rebid'],['rebid']],
    'rebreak':[['rebroke'],['rebroken']],
    'rebuild':[['rebuilt'],['rebuilt']],
    'recast':[['recast'],['recast']],
    'recut':[['recut'],['recut']],
    'redeal':[['redealt'],['redealt']],
    'redo':[['redid'],['redone']],
    'redraw':[['redrew'],['redrawn']],
    'refind':[['refound'],['refound']],
    'refreeze':[['refroze'],['refrozen']],
    'regrow':[['regrew'],['regrown']],
    'rehear':[['reheard'],['reheard']],
    'relearn':[['relearned', 'relearnt'],['relearned', 'relearnt']],
    'relight':[['relit', 'relighted'],['relit', 'relighted']],
    'remake':[['remade'],['remade']],
    'rend':[['rent', 'rended'],['rent', 'rended']],
    'repay':[['repaid'],['repaid']],
    'reprove':[['reproved'],['reproved', 'reproven']],
    'reread':[['reread'],['reread']],
    'rerun':[['reran'],['rerun']],
    'resell':[['resold'],['resold']],
    'resend':[['resent'],['resent']],
    'reset':[['reset'],['reset']],
    'reshoe':[['reshod', 'reshoed'],['reshodden', 'reshod', 'reshoed']],
    'reshoot':[['reshot'],['reshot']],
    'reshow':[['reshowed'],['reshown', 'reshowed']],
    'reshut':[['reshut'],['reshut']],
    'resing':[['resang'],['resung']],
    'resit':[['resat'],['resat']],
    'retake':[['retook'],['retaken']],
    'retell':[['retold'],['retold']],
    'rethink':[['rethought'],['rethought']],
    'retread':[['retrod'],['retrodden']],
    'rewed':[['rewed', 'rewedded'],['rewed', 'rewedded']],
    'rewind':[['rewound'],['rewound']],
    'rewrite':[['rewrote'],['rewritten']],
    'rid':[['rid', 'ridded'],['rid', 'ridden', 'ridded']],
    'ride':[['rode'],['ridden']],
    'ring':[['rang'],['rung']],
    'rise':[['rose'],['risen']],
    'rive':[['rived', 'rove'],['rived', 'riven']],
    'run':[['ran'],['run']],
    'saw':[['sawed'],['sawed', 'sawn']],
    'say':[['said'],['said']],
    'see':[['saw'],['seen']],
    'seek':[['sought'],['sought']],
    'seethe':[['seethed'],['seethed']],
    'self-feed':[['self-fed'],['self-fed']],
    'sell':[['sold'],['sold']],
    'send':[['sent'],['sent']],
    'set':[['set'],['set']],
    'sew':[['sewed'],['sewn', 'sewed']],
    'shake':[['shook'],['shaken']],
    'shall':[['should'],[]],
    'shape':[['shaped'],['shaped']],
    'shave':[['shaved'],['shaved', 'shaven']],
    'shear':[['sheared', 'shore'],['shorn', 'sheared']],
    'shed':[['shed'],['shed']],
    'shine':[['shone', 'shined'],['shone', 'shined']],
    'shit':[['shit', 'shitted', 'shat'],['shit', 'shitted', 'shat']],
    'shite':[['shited', 'shit', 'shat'],['shited', 'shitten']],
    'shoe':[['shod', 'shoed'],['shodden', 'shod', 'shoed']],
    'shoot':[['shot'],['shot']],
    'show':[['showed'],['shown']],
    'shrink':[['shrank', 'shrunk'],['shrunk', 'shrunken']],
    'shut':[['shut'],['shut']],
    'sight-read':[['sight-read'],['sight-read']],
    'sightsee':[['sightsaw'],['sightseen']],
    'simulcast':[['simulcast', 'simulcasted'],['simulcast', 'simulcasted']],
    'sing':[['sang'],['sung']],
    'sink':[['sank', 'sunk'],['sunk', 'sunken']],
    'sit':[['sat'],['sat']],
    'slay':[['slew', 'slayed'],['slain', 'slayed']],
    'sleep':[['slept'],['slept']],
    'slide':[['slid'],['slid', 'slidden']],
    'sling':[['slung'],['slung']],
    'slink':[['slunk', 'slinked', 'slank'],['slunk', 'slinked', 'slank']],
    'slip':[['slipped'],['slipped']],
    'slit':[['slit'],['slit', 'slitten']],
    'smell':[['smelled', 'smelt'],['smelled', 'smelt']],
    'smite':[['smote'],['smitten', 'smited']],
    'sneak':[['sneaked', 'snuck'],['sneaked', 'snuck']],
    'soothsay':[['soothsaid'],['soothsaid']],
    'sow':[['sowed'],['sown', 'sowed']],
    'speak':[['spoke'],['spoken']],
    'speed':[['sped', 'speeded'],['sped', 'speeded']],
    'spell':[['spelled', 'spelt'],['spelled', 'spelt']],
    'spend':[['spent'],['spent']],
    'spill':[['spilled', 'spilt'],['spilled', 'spilt']],
    'spin':[['spun'],['spun']],
    'spit':[['spat', 'spit'],['spat', 'spit']],
    'split':[['split'],['split']],
    'spoil':[['spoiled', 'spoilt'],['spoiled', 'spoilt']],
    'spoon-feed':[['spoon-fed'],['spoon-fed']],
    'spread':[['spread'],['spread']],
    'spring':[['sprang', 'sprung'],['sprung']],
    'stand':[['stood'],['stood']],
    'starve':[['starved'],['starved']],
    'stave':[['stove', 'staved'],['stove', 'staved']],
    'stay':[['stayed'],['stayed']],
    'steal':[['stole'],['stolen']],
    'stick':[['stuck'],['stuck']],
    'sting':[['stung'],['stung']],
    'stink':[['stank', 'stunk'],['stunk']],
    'stretch':[['stretched'],['stretched']],
    'strew':[['strewed'],['strewn', 'strewed']],
    'stride':[['strode'],['stridden']],
    'strike':[['struck'],['struck', 'stricken']],
    'string':[['strung'],['strung']],
    'strip':[['stripped', 'stript'],['stripped', 'stript']],
    'strive':[['strove', 'strived'],['striven', 'strived']],
    'sublet':[['sublet'],['sublet']],
    'sunburn':[['sunburned', 'sunburnt'],['sunburned', 'sunburnt']],
    'swear':[['swore'],['sworn']],
    'sweat':[['sweated', 'sweat'],['sweated', 'sweat']],
    'sweep':[['swept'],['swept']],
    'swell':[['swelled'],['swollen', 'swelled']],
    'swim':[['swam'],['swum']],
    'swing':[['swang', 'swung'],['swung']],
    'take':[['took'],['taken']],
    'teach':[['taught'],['taught']],
    'tear':[['tore'],['torn']],
    'telecast':[['telecast', 'telecasted'],['telecast', 'telecasted']],
    'tell':[['told'],['told']],
    'test-drive':[['test-drove'],['test-driven']],
    'test-fly':[['test-flew'],['test-flown']],
    'think':[['thought'],['thought']],
    'thrive':[['throve', 'thrived'],['thriven', 'thrived']],
    'throw':[['threw'],['thrown']],
    'thrust':[['thrust', 'thrusted'],['thrust', 'thrusted']],
    'tread':[['trod'],['trodden', 'trod']],
    'typecast':[['typecast', 'typecasted'],['typecast', 'typecasted']],
    'unbend':[['unbent'],['unbent']],
    'unbind':[['unbound'],['unbound']],
    'unclothe':[['unclad', 'unclothed'],['unclad', 'unclothed']],
    'underbear':[['underbore'],['underborne', 'underborn']],
    'underbet':[['underbet'],['underbet']],
    'underbid':[['underbid'],['underbid']],
    'underbind':[['underbound'],['underbound']],
    'underbuild':[['underbuilt'],['underbuilt']],
    'underbuy':[['underbought'],['underbought']],
    'undercast':[['undercast'],['undercast']],
    'underclothe':[['underclad', 'underclothed'],['underclad', 'underclothed']],
    'undercut':[['undercut'],['undercut']],
    'underdig':[['underdug'],['underdug']],
    'underdo':[['underdid'],['underdone']],
    'underdraw':[['underdrew'],['underdrawn']],
    'undereat':[['underate'],['undereaten']],
    'underfeed':[['underfed'],['underfed']],
    'undergird':[['undergirded'],['undergirded']],
    'undergo':[['underwent'],['undergone']],
    'undergrow':[['undergrew'],['undergrown']],
    'underhang':[['underhung', 'underhanged'],['underhung', 'underhanged']],
    'underhit':[['underhit'],['underhit']],
    'underkeep':[['underkept'],['underkept']],
    'underlay':[['underlaid'],['underlaid']],
    'underlead':[['underled'],['underled']],
    'underlie':[['underlay'],['underlain']],
    'underpay':[['underpaid'],['underpaid']],
    'underrun':[['underran'],['underrun']],
    'undersee':[['undersaw'],['underseen']],
    'undersell':[['undersold'],['undersold']],
    'undershoot':[['undershot'],['undershot']],
    'undersleep':[['underslept'],['underslept']],
    'underspread':[['underspread'],['underspread']],
    'understand':[['understood'],['understood']],
    'undertake':[['undertook'],['undertaken']],
    'underthrow':[['underthrew'],['underthrown']],
    'underwrite':[['underwrote'],['underwritten']],
    'undo':[['undid'],['undone']],
    'unfreeze':[['unfroze'],['unfrozen']],
    'unhear':[['unheard'],['unheard']],
    'unlay':[['unlaid'],['unlaid']],
    'unlearn':[['unlearned', 'unlearnt'],['unlearned', 'unlearnt']],
    'unmake':[['unmade'],['unmade']],
    'unwind':[['unwound'],['unwound']],
    'upcast':[['upcast', 'upcasted'],['upcast', 'upcasted']],
    'updraw':[['updrew'],['updrawn']],
    'upgrow':[['upgrew'],['upgrown']],
    'uphang':[['uphung', 'uphanged'],['uphung', 'uphanged']],
    'upheave':[['upheaved', 'uphove'],['upheaved']],
    'uphold':[['upheld'],['upheld']],
    'uprise':[['uprose'],['uprisen']],
    'upsell':[['upsold'],['upsold']],
    'upset':[['upset'],['upset']],
    'upstand':[['upstood'],['upstood']],
    'upsweep':[['upswept'],['upswept']],
    'upswell':[['upswelled'],['upswollen', 'upswelled']],
    'uptear':[['uptore'],['uptorn']],
    'upthrow':[['upthrew'],['upthrown']],
    'vex':[['vexed'],['vexed']],
    'wake':[['woke'],['woken']],
    'wax':[['waxed'],['waxed']],
    'waylay':[['waylaid'],['waylaid']],
    'wear':[['weared', 'wore'],['weared', 'worn']],
    'weave':[['wove', 'weaved'],['woven', 'weaved']],
    'webcast':[['webcast'],['webcast']],
    'wed':[['wed', 'wedded'],['wed', 'wedded']],
    'weep':[['wept', 'weeped'],['wept', 'weeped']],
    'wend':[['wended'],['wended']],
    'wet':[['wet', 'wetted'],['wet', 'wetted']],
    'will':[['would'],[]],
    'win':[['won'],['won']],
    'wind':[['wound'],['wound']],
    'withdraw':[['withdrew'],['withdrawn']],
    'withhold':[['withheld'],['withheld']],
    'withstand':[['withstood'],['withstood']],
    'work':[['worked'],['worked']],
    'wreak':[['wreaked', 'wrought'],['wreaked', 'wrought']],
    'wring':[['wrang', 'wrung'],['wrung']],
    'write':[['wrote'],['written']],
    'writhe':[['writhed'],['writhed']],
    'zinc':[['zinced', 'zinked', 'zincked'],['zinced', 'zinked', 'zincked']],
}

INFLECTION_MAP = {
    'abided':'abide',
    'ached':'ache',
    'alit':'alight',
    'alighted':'alight',
    'arose':'arise',
    'arisen':'arise',
    'awoke':'awake',
    'awoken':'awake',
    'babysat':'babysit',
    'backlit':'backlight',
    'backlighted':'backlight',
    'backslid':'backslide',
    'backslided':'backslide',
    'backslidden':'backslide',
    'was':'be',
    'were':'be',
    'been':'be',
    'bore':'bear',
    'borne':'bear',
    'born':'bear',
    'beat':'beat',
    'beaten':'beat',
    'became':'become',
    'become':'become',
    'bedid':'bedo',
    'bedone':'bedo',
    'bedrew':'bedraw',
    'bedrawn':'bedraw',
    'bedreamed':'bedream',
    'bedreamt':'bedream',
    'bedrove':'bedrive',
    'bedriven':'bedrive',
    'bedwelt':'bedwell',
    'bedwelled':'bedwell',
    'befell':'befall',
    'befallen':'befall',
    'befought':'befight',
    'began':'begin',
    'begun':'begin',
    'beheard':'behear',
    'beheld':'behold',
    'bekenned':'beken',
    'bekent':'beken',
    'beknit':'beknit',
    'beknitted':'beknit',
    'belaid':'belay',
    'beleaped':'beleap',
    'beleapt':'beleap',
    'beleft':'beleave',
    'bent':'bend',
    'bequeathed':'bequeath',
    'bequethed':'bequeath',
    'bequoth':'bequeath',
    'bequod':'bequeath',
    'bequethen':'bequeath',
    'bereaved':'bereave',
    'bereft':'bereave',
    'beseeched':'beseech',
    'besought':'beseek',
    'beset':'beset',
    'bespoke':'bespeak',
    'bespoken':'bespeak',
    'bestrewed':'bestrew',
    'bestrewn':'bestrew',
    'bestrode':'bestride',
    'bestridden':'bestride',
    'bet':'bet',
    'betted':'bet',
    'betook':'betake',
    'betaken':'betake',
    'beteed':'betee',
    'betow':'betee',
    'betown':'betee',
    'betided':'betide',
    'bid':'bid',
    'bided':'bide',
    'bode':'bide',
    'bidden':'bide',
    'bound':'bind',
    'bit':'bite',
    'bitten':'bite',
    'bled':'bleed',
    'blended':'blend',
    'blessed':'bless',
    'blew':'blow',
    'blown':'blow',
    'bottle-fed':'bottle-feed',
    'broke':'break',
    'broken':'break',
    'breastfed':'breastfeed',
    'bred':'breed',
    'brought':'bring',
    'broadcast':'broadcast',
    'broadcasted':'broadcast',
    'browbeat':'browbeat',
    'browbeaten':'browbeat',
    'built':'build',
    'burned':'burn',
    'burnt':'burn',
    'burst':'burst',
    'busted':'bust',
    'bust':'bust',
    'bought':'buy',
    'could':'can',
    'cast':'cast',
    'caught':'catch',
    'chided':'chide',
    'chid':'chide',
    'chidden':'chide',
    'chose':'choose',
    'chosen':'choose',
    'clad':'clothe',
    'cladded':'clad',
    'clapped':'clap',
    'clearcut':'clearcut',
    'cleft':'cleave',
    'clove':'cleave',
    'cleaved':'cleave',
    'cloven':'cleave',
    'clung':'cling',
    'clothed':'clothe',
    'combed':'comb',
    'kempt':'comb',
    'came':'come',
    'come':'come',
    'comen':'come',
    'cost':'cost',
    'costed':'cost',
    'cowrote':'cowrite',
    'cowritten':'cowrite',
    'crept':'creep',
    'creeped':'creep',
    'crosscut':'crosscut',
    'crowed':'crow',
    'crew':'crow',
    'cut':'cut',
    'dared':'dare',
    'dealt':'deal',
    'dug':'dig',
    'dived':'dive',
    'dove':'dive',
    'did':'do',
    'done':'do',
    'dowed':'dow',
    'dought':'dow',
    'downcast':'downcast',
    'downcasted':'downcast',
    'downdrew':'downdraw',
    'downdrawn':'downdraw',
    'dragged':'drag',
    'drew':'draw',
    'drawn':'draw',
    'dreamed':'dream',
    'dreamt':'dream',
    'dressed':'dress',
    'drank':'drink',
    'drunk':'drink',
    'drove':'drive',
    'driven':'drive',
    'dwelt':'dwell',
    'dwelled':'dwell',
    'earned':'earn',
    'earnt':'earn',
    'ate':'eat',
    'eaten':'eat',
    'fell':'fall',
    'fallen':'fall',
    'fed':'feed',
    'felt':'feel',
    'fought':'fight',
    'found':'find',
    'fitted':'fit',
    'fit':'fit',
    'fled':'flee',
    'flung':'fling',
    'flew':'fly',
    'flown':'fly',
    'forbore':'forbear',
    'forborne':'forbear',
    'forborn':'forbear',
    'forbid':'forbid',
    'forbade':'forbid',
    'forbad':'forbid',
    'forbidden':'forbid',
    'force-fed':'force-feed',
    'forecast':'forecast',
    'forecasted':'forecast',
    'forefelt':'forefeel',
    'forewent':'forego',
    'foregone':'forego',
    'foreheard':'forehear',
    'forekenned':'foreken',
    'forekent':'foreken',
    'foreknew':'foreknow',
    'foreknown':'foreknow',
    'foresaw':'foresee',
    'foreseen':'foresee',
    'foreshowed':'foreshow',
    'foreshown':'foreshow',
    'foretold':'foretell',
    'forgot':'forget',
    'forgotten':'forget',
    'forgave':'forgive',
    'forgiven':'forgive',
    'forwent':'forgo',
    'forgone':'forgo',
    'forsook':'forsake',
    'forsaken':'forsake',
    'forstood':'forstand',
    'forswore':'forswear',
    'forsworn':'forswear',
    'forteed':'fortee',
    'fortow':'fortee',
    'fortown':'fortee',
    'forthcame':'forthcome',
    'forthcome':'forthcome',
    'forthleaped':'forthleap',
    'forthleapt':'forthleap',
    'forthtold':'forthtell',
    'froze':'freeze',
    'frozen':'freeze',
    'fretted':'fret',
    'frate':'fret',
    'fretten':'fret',
    'frostbit':'frostbite',
    'frostbitten':'frostbite',
    'got':'get',
    'gotten':'get',
    'ghostwrote':'ghostwrite',
    'ghostwritten':'ghostwrite',
    'gilded':'gild',
    'gilt':'gild',
    'girded':'gird',
    'gave':'give',
    'given':'give',
    'went':'go',
    'gone':'go',
    'green-lit':'green-light',
    'green-lighted':'green-light',
    'ground':'grind',
    'grinded':'grind',
    'grew':'grow',
    'grown':'grow',
    'hamstrung':'hamstring',
    'hand-fed':'hand-feed',
    'hand-knit':'hand-knit',
    'hand-knitted':'hand-knit',
    'handset':'handset',
    'handsewed':'handsew',
    'handsewn':'handsew',
    'handsprang':'handspring',
    'handsprung':'handspring',
    'handwrote':'handwrite',
    'handwritten':'handwrite',
    'hung':'hang',
    'hanged':'hang',
    'had':'have',
    'heard':'hear',
    'heaved':'heave',
    'helped':'help',
    'hewed':'hew',
    'hewn':'hew',
    'hid':'hide',
    'hidden':'hide',
    'hit':'hit',
    'hoisted':'hoist',
    'hoist':'hoist',
    'held':'hold',
    'housesat':'housesit',
    'hurt':'hurt',
    'inbred':'inbreed',
    'inheld':'inhold',
    'inlaid':'inlay',
    'inled':'inlead',
    'input':'input',
    'inputted':'input',
    'inset':'inset',
    'insetted':'inset',
    'intook':'intake',
    'intaken':'intake',
    'interbred':'interbreed',
    'intercut':'intercut',
    'interlaid':'interlay',
    'interwove':'interweave',
    'interweaved':'interweave',
    'interwoven':'interweave',
    'kept':'keep',
    'kenned':'ken',
    'kent':'ken',
    'knelt':'kneel',
    'kneeled':'kneel',
    'knit':'knit',
    'knitted':'knit',
    'knew':'know',
    'known':'know',
    'laded':'lade',
    'laden':'lade',
    'laughed':'laugh',
    'laid':'lay',
    'led':'lead',
    'leaned':'lean',
    'leant':'lean',
    'leaped':'leap',
    'leapt':'leap',
    'learned':'learn',
    'learnt':'learn',
    'left':'leave',
    'lent':'lend',
    'let':'let',
    'lay':'lie',
    'lain':'lie',
    'lit':'light',
    'lighted':'light',
    'lipread':'lipread',
    'lost':'lose',
    'made':'make',
    'might':'may',
    'meant':'mean',
    'met':'meet',
    'melted':'melt',
    'molten':'melt',
    'misbecame':'misbecome',
    'misbecome':'misbecome',
    'misbegot':'misbeget',
    'misbegotten':'misbeget',
    'miscast':'miscast',
    'mischose':'mischoose',
    'mischosen':'mischoose',
    'misdealt':'misdeal',
    'misdid':'misdo',
    'misdone':'misdo',
    'misfed':'misfeed',
    'misfitted':'misfit',
    'misfit':'misfit',
    'misgave':'misgive',
    'misgiven':'misgive',
    'misheard':'mishear',
    'mishit':'mishit',
    'misheld':'mishold',
    'miskept':'miskeep',
    'miskenned':'misken',
    'miskent':'misken',
    'misknew':'misknow',
    'misknown':'misknow',
    'mislaid':'mislay',
    'misled':'mislead',
    'mislearned':'mislearn',
    'mislearnt':'mislearn',
    'misread':'misread',
    'missaid':'missay',
    'missaw':'missee',
    'misseen':'missee',
    'missent':'missend',
    'misset':'misset',
    'misshaped':'misshape',
    'misshot':'misshoot',
    'misspoke':'misspeak',
    'misspoken':'misspeak',
    'misspelled':'misspell',
    'misspelt':'misspell',
    'misspent':'misspend',
    'mistook':'mistake',
    'mistaken':'mistake',
    'mistold':'mistell',
    'misthrew':'misthrow',
    'misthrown':'misthrow',
    'misunderstood':'misunderstand',
    'miswed':'miswed',
    'miswedded':'miswed',
    'miswrote':'miswrite',
    'miswritten':'miswrite',
    'mixed':'mix',
    'mowed':'mow',
    'mown':'mow',
    'needed':'need',
    'offled':'offlead',
    'offset':'offset',
    'offsetted':'offset',
    'onlaid':'onlay',
    'onled':'onlead',
    'outbid':'outbid',
    'outbidden':'outbid',
    'outbroke':'outbreak',
    'outbroken':'outbreak',
    'outdid':'outdo',
    'outdone':'outdo',
    'outdrew':'outdraw',
    'outdrawn':'outdraw',
    'outdrank':'outdrink',
    'outdrunk':'outdrink',
    'outdwelt':'outdwell',
    'outdwelled':'outdwell',
    'outate':'outeat',
    'outeaten':'outeat',
    'outfell':'outfall',
    'outfallen':'outfall',
    'outfought':'outfight',
    'outflew':'outfly',
    'outflown':'outfly',
    'outgrew':'outgrow',
    'outgrown':'outgrow',
    'outheard':'outhear',
    'outkenned':'outken',
    'outkent':'outken',
    'outlaid':'outlay',
    'outled':'outlead',
    'outleaped':'outleap',
    'outleapt':'outleap',
    'output':'output',
    'outputted':'output',
    'outrode':'outride',
    'outridden':'outride',
    'outran':'outrun',
    'outrun':'outrun',
    'outsold':'outsell',
    'outshone':'outshine',
    'outshined':'outshine',
    'outspent':'outspend',
    'outspun':'outspin',
    'outspread':'outspread',
    'outstrode':'outstride',
    'outstridden':'outstride',
    'outstrove':'outstrive',
    'outstriven':'outstrive',
    'outswore':'outswear',
    'outsworn':'outswear',
    'outswam':'outswim',
    'outswum':'outswim',
    'outthought':'outthink',
    'outthrew':'outthrow',
    'outthrown':'outthrow',
    'outthrusted':'outthrust',
    'outweared':'outwear',
    'outwore':'outwear',
    'outworn':'outwear',
    'overbore':'overbear',
    'overborne':'overbear',
    'overborn':'overbear',
    'overbeat':'overbeat',
    'overbeaten':'overbeat',
    'overbent':'overbend',
    'overbid':'overbid',
    'overblew':'overblow',
    'overblown':'overblow',
    'overbred':'overbreed',
    'overbuilt':'overbuild',
    'overbought':'overbuy',
    'overcast':'overcast',
    'overclad':'overclothe',
    'overclothed':'overclothe',
    'overcame':'overcome',
    'overcome':'overcome',
    'overcomen':'overcome',
    'overdid':'overdo',
    'overdone':'overdo',
    'overdrew':'overdraw',
    'overdrawn':'overdraw',
    'overdrank':'overdrink',
    'overdrunk':'overdrink',
    'overdrove':'overdrive',
    'overdriven':'overdrive',
    'overate':'overeat',
    'overeaten':'overeat',
    'overfed':'overfeed',
    'overflew':'overfly',
    'overflown':'overfly',
    'overgave':'overgive',
    'overgiven':'overgive',
    'overgrew':'overgrow',
    'overgrown':'overgrow',
    'overhung':'overhang',
    'overhanged':'overhang',
    'overheard':'overhear',
    'overhit':'overhit',
    'overkept':'overkeep',
    'overladed':'overlade',
    'overladen':'overlade',
    'overlaid':'overlay',
    'overlayed':'overlay',
    'overled':'overlead',
    'overleaped':'overleap',
    'overleapt':'overleap',
    'overlearned':'overlearn',
    'overlearnt':'overlearn',
    'overleft':'overleave',
    'overlay':'overlie',
    'overlain':'overlie',
    'overpaid':'overpay',
    'overrode':'override',
    'overridden':'override',
    'overran':'overrun',
    'overrun':'overrun',
    'oversaw':'oversee',
    'overseen':'oversee',
    'oversold':'oversell',
    'overset':'overset',
    'oversewed':'oversew',
    'oversewn':'oversew',
    'overshook':'overshake',
    'overshaken':'overshake',
    'overshone':'overshine',
    'overshined':'overshine',
    'overshot':'overshoot',
    'overshrank':'overshrink',
    'overshrunk':'overshrink',
    'overshrunken':'overshrink',
    'overslept':'oversleep',
    'overslid':'overslide',
    'overslidden':'overslide',
    'overspent':'overspend',
    'overspilled':'overspill',
    'overspilt':'overspill',
    'overspread':'overspread',
    'overstood':'overstand',
    'overstrewed':'overstrew',
    'overstrewn':'overstrew',
    'overstrode':'overstride',
    'overstridden':'overstride',
    'overstruck':'overstrike',
    'overstricken':'overstrike',
    'overstrung':'overstring',
    'overstrove':'overstrive',
    'overstriven':'overstrive',
    'overswang':'overswing',
    'overswung':'overswing',
    'overtook':'overtake',
    'overtaken':'overtake',
    'overthrew':'overthrow',
    'overthrown':'overthrow',
    'overweared':'overwear',
    'overwore':'overwear',
    'overworn':'overwear',
    'overwet':'overwet',
    'overwetted':'overwet',
    'overworked':'overwork',
    'overwrought':'overwork',
    'overwrote':'overwrite',
    'overwritten':'overwrite',
    'partook':'partake',
    'partaken':'partake',
    'paid':'pay',
    'penned':'pen',
    'pent':'pen',
    'pleaded':'plead',
    'pled':'plead',
    'plead':'plead',
    'podcast':'podcast',
    'podcasted':'podcast',
    'precast':'precast',
    'prepaid':'prepay',
    'prepayed':'prepay',
    'preset':'preset',
    'proofread':'proofread',
    'proved':'prove',
    'proven':'prove',
    'put':'put',
    'quick-froze':'quick-freeze',
    'quick-frozen':'quick-freeze',
    'quit':'quit',
    'quitted':'quit',
    're-laid':'re-lay',
    'reached':'reach',
    'read':'read',
    'rebid':'rebid',
    'rebroke':'rebreak',
    'rebroken':'rebreak',
    'rebuilt':'rebuild',
    'recast':'recast',
    'recut':'recut',
    'redealt':'redeal',
    'redid':'redo',
    'redone':'redo',
    'redrew':'redraw',
    'redrawn':'redraw',
    'refound':'refind',
    'refroze':'refreeze',
    'refrozen':'refreeze',
    'regrew':'regrow',
    'regrown':'regrow',
    'reheard':'rehear',
    'relearned':'relearn',
    'relearnt':'relearn',
    'relit':'relight',
    'relighted':'relight',
    'remade':'remake',
    'rent':'rend',
    'rended':'rend',
    'repaid':'repay',
    'reproved':'reprove',
    'reproven':'reprove',
    'reread':'reread',
    'reran':'rerun',
    'rerun':'rerun',
    'resold':'resell',
    'resent':'resend',
    'reset':'reset',
    'reshod':'reshoe',
    'reshoed':'reshoe',
    'reshodden':'reshoe',
    'reshot':'reshoot',
    'reshowed':'reshow',
    'reshown':'reshow',
    'reshut':'reshut',
    'resang':'resing',
    'resung':'resing',
    'resat':'resit',
    'retook':'retake',
    'retaken':'retake',
    'retold':'retell',
    'rethought':'rethink',
    'retrod':'retread',
    'retrodden':'retread',
    'rewed':'rewed',
    'rewedded':'rewed',
    'rewound':'rewind',
    'rewrote':'rewrite',
    'rewritten':'rewrite',
    'rid':'rid',
    'ridded':'rid',
    'ridden':'ride',
    'rode':'ride',
    'rang':'ring',
    'rung':'ring',
    'rose':'rise',
    'risen':'rise',
    'rived':'rive',
    'rove':'rive',
    'riven':'rive',
    'ran':'run',
    'run':'run',
    'sawed':'saw',
    'sawn':'saw',
    'said':'say',
    'saw':'see',
    'seen':'see',
    'sought':'seek',
    'seethed':'seethe',
    'self-fed':'self-feed',
    'sold':'sell',
    'sent':'send',
    'set':'set',
    'sewed':'sew',
    'sewn':'sew',
    'shook':'shake',
    'shaken':'shake',
    'should':'shall',
    'shaped':'shape',
    'shaved':'shave',
    'shaven':'shave',
    'sheared':'shear',
    'shore':'shear',
    'shorn':'shear',
    'shed':'shed',
    'shone':'shine',
    'shined':'shine',
    'shit':'shite',
    'shitted':'shit',
    'shat':'shite',
    'shited':'shite',
    'shitten':'shite',
    'shod':'shoe',
    'shoed':'shoe',
    'shodden':'shoe',
    'shot':'shoot',
    'showed':'show',
    'shown':'show',
    'shrank':'shrink',
    'shrunk':'shrink',
    'shrunken':'shrink',
    'shut':'shut',
    'sight-read':'sight-read',
    'sightsaw':'sightsee',
    'sightseen':'sightsee',
    'simulcast':'simulcast',
    'simulcasted':'simulcast',
    'sang':'sing',
    'sung':'sing',
    'sank':'sink',
    'sunk':'sink',
    'sunken':'sink',
    'sat':'sit',
    'slew':'slay',
    'slayed':'slay',
    'slain':'slay',
    'slept':'sleep',
    'slid':'slide',
    'slidden':'slide',
    'slung':'sling',
    'slunk':'slink',
    'slinked':'slink',
    'slank':'slink',
    'slipped':'slip',
    'slit':'slit',
    'slitten':'slit',
    'smelled':'smell',
    'smelt':'smell',
    'smote':'smite',
    'smitten':'smite',
    'smited':'smite',
    'sneaked':'sneak',
    'snuck':'sneak',
    'soothsaid':'soothsay',
    'sowed':'sow',
    'sown':'sow',
    'spoke':'speak',
    'spoken':'speak',
    'sped':'speed',
    'speeded':'speed',
    'spelled':'spell',
    'spelt':'spell',
    'spent':'spend',
    'spilled':'spill',
    'spilt':'spill',
    'spun':'spin',
    'spat':'spit',
    'spit':'spit',
    'split':'split',
    'spoiled':'spoil',
    'spoilt':'spoil',
    'spoon-fed':'spoon-feed',
    'spread':'spread',
    'sprang':'spring',
    'sprung':'spring',
    'stood':'stand',
    'starved':'starve',
    'stove':'stave',
    'staved':'stave',
    'stayed':'stay',
    'stole':'steal',
    'stolen':'steal',
    'stuck':'stick',
    'stung':'sting',
    'stank':'stink',
    'stunk':'stink',
    'stretched':'stretch',
    'strewed':'strew',
    'strewn':'strew',
    'strode':'stride',
    'stridden':'stride',
    'struck':'strike',
    'stricken':'strike',
    'strung':'string',
    'stripped':'strip',
    'stript':'strip',
    'strove':'strive',
    'strived':'strive',
    'striven':'strive',
    'sublet':'sublet',
    'sunburned':'sunburn',
    'sunburnt':'sunburn',
    'swore':'swear',
    'sworn':'swear',
    'sweated':'sweat',
    'sweat':'sweat',
    'swept':'sweep',
    'swelled':'swell',
    'swollen':'swell',
    'swam':'swim',
    'swum':'swim',
    'swang':'swing',
    'swung':'swing',
    'took':'take',
    'taken':'take',
    'taught':'teach',
    'tore':'tear',
    'torn':'tear',
    'telecast':'telecast',
    'telecasted':'telecast',
    'told':'tell',
    'test-drove':'test-drive',
    'test-driven':'test-drive',
    'test-flew':'test-fly',
    'test-flown':'test-fly',
    'thought':'think',
    'throve':'thrive',
    'thrived':'thrive',
    'thriven':'thrive',
    'threw':'throw',
    'thrown':'throw',
    'thrust':'thrust',
    'thrusted':'thrust',
    'trod':'tread',
    'trodden':'tread',
    'typecast':'typecast',
    'typecasted':'typecast',
    'unbent':'unbend',
    'unbound':'unbind',
    'unclad':'unclothe',
    'unclothed':'unclothe',
    'underbore':'underbear',
    'underborne':'underbear',
    'underborn':'underbear',
    'underbet':'underbet',
    'underbid':'underbid',
    'underbound':'underbind',
    'underbuilt':'underbuild',
    'underbought':'underbuy',
    'undercast':'undercast',
    'underclad':'underclothe',
    'underclothed':'underclothe',
    'undercut':'undercut',
    'underdug':'underdig',
    'underdid':'underdo',
    'underdone':'underdo',
    'underdrew':'underdraw',
    'underdrawn':'underdraw',
    'underate':'undereat',
    'undereaten':'undereat',
    'underfed':'underfeed',
    'undergirded':'undergird',
    'underwent':'undergo',
    'undergone':'undergo',
    'undergrew':'undergrow',
    'undergrown':'undergrow',
    'underhung':'underhang',
    'underhanged':'underhang',
    'underhit':'underhit',
    'underkept':'underkeep',
    'underlaid':'underlay',
    'underled':'underlead',
    'underlay':'underlie',
    'underlain':'underlie',
    'underpaid':'underpay',
    'underran':'underrun',
    'underrun':'underrun',
    'undersaw':'undersee',
    'underseen':'undersee',
    'undersold':'undersell',
    'undershot':'undershoot',
    'underslept':'undersleep',
    'underspread':'underspread',
    'understood':'understand',
    'undertook':'undertake',
    'undertaken':'undertake',
    'underthrew':'underthrow',
    'underthrown':'underthrow',
    'underwrote':'underwrite',
    'underwritten':'underwrite',
    'undid':'undo',
    'undone':'undo',
    'unfroze':'unfreeze',
    'unfrozen':'unfreeze',
    'unheard':'unhear',
    'unlaid':'unlay',
    'unlearned':'unlearn',
    'unlearnt':'unlearn',
    'unmade':'unmake',
    'unwound':'unwind',
    'upcast':'upcast',
    'upcasted':'upcast',
    'updrew':'updraw',
    'updrawn':'updraw',
    'upgrew':'upgrow',
    'upgrown':'upgrow',
    'uphung':'uphang',
    'uphanged':'uphang',
    'upheaved':'upheave',
    'uphove':'upheave',
    'upheld':'uphold',
    'uprose':'uprise',
    'uprisen':'uprise',
    'upsold':'upsell',
    'upset':'upset',
    'upstood':'upstand',
    'upswept':'upsweep',
    'upswelled':'upswell',
    'upswollen':'upswell',
    'uptore':'uptear',
    'uptorn':'uptear',
    'upthrew':'upthrow',
    'upthrown':'upthrow',
    'vexed':'vex',
    'woke':'wake',
    'woken':'wake',
    'waxed':'wax',
    'waylaid':'waylay',
    'weared':'wear',
    'wore':'wear',
    'worn':'wear',
    'wove':'weave',
    'weaved':'weave',
    'woven':'weave',
    'webcast':'webcast',
    'wed':'wed',
    'wedded':'wed',
    'wept':'weep',
    'weeped':'weep',
    'wended':'wend',
    'wet':'wet',
    'wetted':'wet',
    'would':'will',
    'won':'win',
    'wound':'wind',
    'withdrew':'withdraw',
    'withdrawn':'withdraw',
    'withheld':'withhold',
    'withstood':'withstand',
    'worked':'work',
    'wreaked':'wreak',
    'wrought':'wreak',
    'wrang':'wring',
    'wrung':'wring',
    'wrote':'write',
    'written':'write',
    'writhed':'writhe',
    'zinced':'zinc',
    'zinked':'zinc',
    'zincked':'zinc',
}
